version: '3.9'

services:
  catalogdb:
    image: mongo
    networks:
      - microaspnet
  basketdb:
    image: redis:alpine
    networks:
      - microaspnet
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    networks:
      - microaspnet
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    networks:
      - microaspnet
    
volumes:
  mongo_data:
    
networks:
  microaspnet:
    name: "microsvc-formation"