version: '3.9'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"    
    volumes:
      - mongo_data:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6381:6379"
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=discount_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  catalog.api:
    container_name: catalog.api    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings:DatabaseName=ProductDb"
      - "DatabaseSettings:CollectionName=Products"
    depends_on:
      - catalogdb
    ports:
      - "8001:80"
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RedisConnectionSettings:ConnectionString=basketdb:6381"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
    depends_on:
      - basketdb
    ports:
      - "8002:80"
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=discount_db;User Id=admin;Password=admin"
    depends_on:
      - discountdb
    ports:
      - "8003:80"
  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=discount_db;User Id=admin;Password=admin"
    depends_on:
      - discountdb
    ports:
      - "8004:80"
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=localhost;Database=OrderDb;User Id=microasp;Password=microasp"
    ports:
      - "8005:80"
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
     